### ISSUE TITLE
not working with 2021.1

### ISSUE THREAD

**Issue by vortex1024** [tspivey/partialLines#1]
addon is not working with 2021.1. 
  File "E:\nvda\userConfig\addons\partialLines\globalPlugins\partialLines.py", line 39, in _caretScriptPostMovedHelper
    speech.speakTextInfo(info, unit=speakUnit, reason=controlTypes.REASON_CARET)
AttributeError: module 'controlTypes' has no attribute 'REASON_CARET'
I think it is due to this constant becoming part of an enum.
Also, manifest needs to be updated.
